name: Change Wombat Serial Number
on: push

concurrency:
group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
cancel-in-progress: true

jobs:
changeSerialNumber:
name: Wombat Serial Number
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
  with:
    fetch-depth: 11 # This value must be set if the lookback configuration option is not disabled for find-code-references. Read more: https://github.com/launchdarkly/ld-find-code-refs#searching-for-unused-flags-extinctions
- name: Wombat Serial Number
  uses: actions/checkout@v2
  with:
    accessToken: ${{ secrets.WS_ACCESS_TOKEN }}
    projKey: SERIAL_NUM
